# Generated by Django 6.0.1 on 2026-02-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_adress_order_city_order_phone_order_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
